### PR TITLE
Added simple player controls and screen collision

### PR DESCRIPTION
**Pull request by briacp**

### CODE REVIEW

**Comment by ojdon** [comment]
Thanks for taking the time to create this PR. 

Merged! :)

**Comment by briacp** [comment]
Great, thanks !

How barebone do you wnat this template to be, like, how much will be too
much ?

2016-07-07 22:24 GMT+02:00 Ollie notifications@github.com:

> Thanks for taking the time to create this PR.
> 
> Merged! :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ojdon/pico8-boilerplate/pull/1#issuecomment-231196335,
> or mute the thread
> https://github.com/notifications/unsubscribe/AD-jyaIFJvF_2qCIGndS7XELb6hRCBb6ks5qTWCCgaJpZM4JG6nW
> .

## 

briac

**Comment by ojdon** [comment]
I'm not too sure myself, to be honest! :sweat_smile: 

I sort of want to make sure that the template code itself does not obstruct the game developer's actual game creation time too much. 

For example, I don't want them to have to sit there for 5 or 10 minutes stripping out the bits they don't need, as I feel that a project like [Lib-Pico8](https://github.com/clowerweb/Lib-Pico8) would be better suited for larger code.

**Comment by briacp** [comment]
Yeah, I understand. Maybe it could be nice to have different templates for
different kind of games (shoot 'em up, arcade, etc.)

2016-07-07 23:19 GMT+02:00 Ollie notifications@github.com:

> I'm not too sure myself, to be honest! 😅
> 
> I sort of want to make sure that the template code itself does not
> obstruct the game developer's actual game creation time too much.
> 
> For example, I don't want them to have to sit there for 5 or 10 minutes
> stripping out the bits they don't need, as I feel that a project like
> Lib-Pico8 https://github.com/clowerweb/Lib-Pico8 would be better suited
> for larger code.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ojdon/pico8-boilerplate/pull/1#issuecomment-231210672,
> or mute the thread
> https://github.com/notifications/unsubscribe/AD-jyX6aTDdAazzrpxru1antCgGMcrpFks5qTW1vgaJpZM4JG6nW
> .

## 

briac

**Pull request merged**
